<?php

namespace Database\Seeders;

use App\Models\Bm2QuestionBank;
use Illuminate\Database\Seeder;

class Bm2QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            // Kindergarten - Addition (Easy)
            [
                'question_text' => 'What is 2 + 3?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => 'K',
                'topic' => 'addition',
                'difficulty' => 'easy',
                'question_format' => 'multiple_choice',
                'options' => ['4', '5', '6', '7'],
                'correct_answer' => '5',
                'explanation' => 'When we add 2 and 3, we get 5.',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 30,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Count on your fingers: 2...3...4...5!'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],
            [
                'question_text' => 'How many apples are there if you have 1 apple and get 2 more?',
                'context_description' => 'You have 1 🍎 and get 2 more 🍎🍎',
                'subject' => 'math',
                'grade_level' => 'K',
                'topic' => 'addition',
                'difficulty' => 'easy',
                'question_format' => 'multiple_choice',
                'options' => ['2', '3', '4', '5'],
                'correct_answer' => '3',
                'explanation' => '1 + 2 = 3',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 45,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Count all the apples together'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Kindergarten - Subtraction (Easy)
            [
                'question_text' => 'What is 5 - 2?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => 'K',
                'topic' => 'subtraction',
                'difficulty' => 'easy',
                'question_format' => 'multiple_choice',
                'options' => ['2', '3', '4', '5'],
                'correct_answer' => '3',
                'explanation' => 'When we take away 2 from 5, we have 3 left.',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 30,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Use your fingers: Put up 5, put down 2'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Grade 1 - Addition (Medium)
            [
                'question_text' => 'What is 7 + 8?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'addition',
                'difficulty' => 'medium',
                'question_format' => 'multiple_choice',
                'options' => ['14', '15', '16', '17'],
                'correct_answer' => '15',
                'explanation' => '7 + 8 = 15. You can think of it as 7 + 3 = 10, then 10 + 5 = 15.',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 45,
                'points_default' => 15,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Make 10 first: 7 + 3 = 10, then add 5 more'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.4,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],
            [
                'question_text' => 'Sarah has 12 stickers. She buys 9 more. How many does she have now?',
                'context_description' => 'Word problem about stickers',
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'addition',
                'difficulty' => 'medium',
                'question_format' => 'multiple_choice',
                'options' => ['19', '20', '21', '22'],
                'correct_answer' => '21',
                'explanation' => '12 + 9 = 21',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 60,
                'points_default' => 15,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Add the ones first: 2 + 9 = 11, then 10 + 11 = 21'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.4,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Grade 1 - Subtraction (Medium)
            [
                'question_text' => 'What is 15 - 7?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'subtraction',
                'difficulty' => 'medium',
                'question_format' => 'multiple_choice',
                'options' => ['6', '7', '8', '9'],
                'correct_answer' => '8',
                'explanation' => '15 - 7 = 8. Think: 7 + ? = 15',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 45,
                'points_default' => 15,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Think: What number plus 7 equals 15?'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.4,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Grade 2 - Addition (Hard)
            [
                'question_text' => 'What is 27 + 35?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '2',
                'topic' => 'addition',
                'difficulty' => 'hard',
                'question_format' => 'multiple_choice',
                'options' => ['52', '62', '72', '82'],
                'correct_answer' => '62',
                'explanation' => '27 + 35 = 62. Add ones: 7+5=12 (carry 1), then tens: 2+3+1=6',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 60,
                'points_default' => 20,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Add the ones first: 7+5=12, write 2 carry 1'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.5,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Grade 2 - Subtraction (Hard)
            [
                'question_text' => 'What is 84 - 37?',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '2',
                'topic' => 'subtraction',
                'difficulty' => 'hard',
                'question_format' => 'multiple_choice',
                'options' => ['37', '47', '57', '67'],
                'correct_answer' => '47',
                'explanation' => '84 - 37 = 47. Borrow from tens: 14-7=7, then 7-3=4',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 60,
                'points_default' => 20,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Borrow from the 8: 14-7=7, then 7-3=4'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.5,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // True/False questions
            [
                'question_text' => 'True or False: 9 + 6 = 15',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'addition',
                'difficulty' => 'easy',
                'question_format' => 'true_false',
                'options' => null,
                'correct_answer' => 'true',
                'explanation' => '9 + 6 does equal 15',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 20,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => false,
                'hints' => null,
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],
            [
                'question_text' => 'True or False: 20 - 8 = 11',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'subtraction',
                'difficulty' => 'medium',
                'question_format' => 'true_false',
                'options' => null,
                'correct_answer' => 'false',
                'explanation' => '20 - 8 = 12, not 11',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 20,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => false,
                'hints' => null,
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],

            // Fill in blank questions
            [
                'question_text' => 'Complete: 6 + ___ = 10',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => 'K',
                'topic' => 'addition',
                'difficulty' => 'easy',
                'question_format' => 'fill_in_blank',
                'options' => null,
                'correct_answer' => '4',
                'explanation' => '6 + 4 = 10',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 30,
                'points_default' => 10,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Count up from 6 to 10'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.3,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],
            [
                'question_text' => 'Find the missing number: 15 - ___ = 8',
                'context_description' => null,
                'subject' => 'math',
                'grade_level' => '1',
                'topic' => 'subtraction',
                'difficulty' => 'medium',
                'question_format' => 'fill_in_blank',
                'options' => null,
                'correct_answer' => '7',
                'explanation' => '15 - 7 = 8',
                'image_url' => null,
                'visual_properties' => null,
                'estimated_time_seconds' => 45,
                'points_default' => 15,
                'allows_calculator' => false,
                'has_hint' => true,
                'hints' => ['Think: 8 + ? = 15'],
                'times_used' => 0,
                'success_rate' => null,
                'discrimination_index' => 0.4,
                'is_active' => true,
                'is_verified' => true,
                'created_by' => 1,
            ],
        ];

        foreach ($questions as $questionData) {
            Bm2QuestionBank::create($questionData);
        }

        $this->command->info('BM2 question bank seeded successfully with 12 questions!');
    }
}
