<template>
  <Head title="My Weekly Plans" />
  <div class="q-pa-md">
    <WeeklyPlanMenu />
    <!-- Page Header -->
    <div class="row items-center q-mb-lg">
      <div class="col">
        <h4 class="q-ma-none text-weight-bold">
          <q-icon name="edit_note" class="q-mr-sm" color="primary" />
          My Weekly Plans
        </h4>
        <p class="text-grey-7 q-mb-none">
          Fill in your classwork and homework for each class
        </p>
      </div>
    </div>

    <!-- Controls -->
    <q-card flat bordered class="q-pa-md q-mb-lg">
      <div class="row q-gutter-md items-center">
        <!-- Week Selector -->
        <div class="col-12 col-sm-6 col-md-4">
          <WeekSelector
            v-model="weekNumber"
            :max-weeks="maxWeeks"
            :current-week="currentWeek"
          />
        </div>

        <!-- Semester -->
        <div class="col-12 col-sm-3 col-md-2">
          <q-select
            v-model="semesterNumber"
            :options="[{ label: 'Semester 1', value: 1 }, { label: 'Semester 2', value: 2 }]"
            label="Semester"
            outlined
            dense
            emit-value
            map-options
          />
        </div>

        <!-- Progress Summary -->
        <div class="col-auto q-ml-auto">
          <q-linear-progress
            :value="completionPercentage / 100"
            size="25px"
            :color="progressColor"
            track-color="grey-3"
            rounded
            style="width: 150px"
          >
            <div class="absolute-full flex flex-center">
              <span class="text-caption text-weight-bold">{{ completionPercentage }}%</span>
            </div>
          </q-linear-progress>
        </div>
      </div>

      <!-- Filters -->
      <div class="row q-gutter-md items-center q-mt-sm">
        <div class="col-12 col-sm-6 col-md-4">
          <q-select
            v-model="selectedClassrooms"
            :options="classroomOptions"
            label="Filter by Classroom"
            outlined
            dense
            multiple
            use-chips
            clearable
          />
        </div>
        <div class="col-12 col-sm-6 col-md-4">
          <q-select
            v-model="selectedDays"
            :options="dayOptions"
            label="Filter by Day"
            outlined
            dense
            multiple
            use-chips
            clearable
            emit-value
            map-options
          />
        </div>
        <!-- Preview & Print Buttons -->
        <div class="col-12 col-sm-6 col-md-auto q-gutter-sm">
          <q-btn
            v-if="selectedClassrooms?.length > 0"
            color="primary"
            label="Preview & Print"
            icon="print"
            @click="showPrintPreview = true"
            outline
          />
        </div>
      </div>
    </q-card>

    <!-- Loading State -->
    <div v-if="loading" class="row justify-center q-pa-xl">
      <q-spinner-dots size="50px" color="primary" />
    </div>

    <!-- Empty State -->
    <q-card v-else-if="!weeklyPlans.length" flat bordered class="text-center q-pa-xl">
      <q-icon name="event_note" size="64px" color="grey-5" />
      <p class="text-h6 text-grey-7 q-mt-md">No plans for this week</p>
      <p class="text-grey-6">Plans will appear once generated by admin</p>
    </q-card>

    <!-- View Tabs -->
    <q-card v-else flat bordered class="q-mb-lg">
      <q-tabs
        v-model="viewTab"
        dense
        class="text-grey-7"
        active-color="primary"
        indicator-color="primary"
        align="left"
      >
        <q-tab name="by-day" label="By Day" icon="calendar_today" />
        <q-tab 
          name="by-classroom" 
          label="By Classroom" 
          icon="meeting_room"
          :disable="!selectedClassrooms || selectedClassrooms.length === 0"
        />
      </q-tabs>
    </q-card>

    <!-- By Day View -->
    <div v-show="viewTab === 'by-day'" class="plans-grid">
      <div v-for="day in sortedPlansByDay" :key="day.dayNumber" class="day-column">
        <div class="day-header">{{ day.dayName }}</div>
        
        <div
          v-for="plan in day.plans"
          :key="plan.id"
          class="plan-card"
          :class="{ 'is-completed': plan.status === 'completed', 'is-partial': plan.status === 'partial' }"
          @click="editPlan(plan)"
        >
          <!-- Subject & Period -->
          <div class="plan-header" :style="getPlanStyle(plan)">
            <span class="period-badge">P{{ plan.schedule?.period_number }}</span>
            <span class="subject-name">{{ plan.schedule?.cst?.subject_name }}</span>
            
            <q-space />
            
            <!-- Copy/Paste Buttons -->
            <div class="flex q-gutter-xs">
              <q-btn
                v-if="copyingPlanId === plan.id"
                icon="close"
                size="xs"
                flat
                round
                color="white"
                @click="(e) => cancelSelection(e)"
              >
                <q-tooltip>Cancel Copy</q-tooltip>
              </q-btn>
              <q-btn
                v-else-if="!copiedData"
                icon="content_copy"
                size="xs"
                flat
                round
                color="white"
                @click="(e) => copyPlan(plan, e)"
              >
                <q-tooltip>Copy CW, HW & Notes</q-tooltip>
              </q-btn>
              <q-btn
                v-if="copiedData && copyingPlanId !== plan.id"
                icon="content_paste"
                size="xs"
                flat
                round
                color="white"
                @click="(e) => pastePlan(plan, e)"
              >
                <q-tooltip>Paste Data</q-tooltip>
              </q-btn>
            </div>
          </div>

          <!-- Classroom -->
          <div class="classroom text-caption text-grey-7">
            <q-icon name="meeting_room" size="xs" />
            {{ plan.schedule?.cst?.classroom_name }}
          </div>

          <!-- Status -->
          <div class="plan-status">
            <StatusBadge :status="plan.status" />
          </div>

          <!-- Preview -->
          <div v-if="plan.cw || plan.hw" class="plan-preview text-caption">
            <div v-if="plan.cw" class="preview-item">
              <q-icon name="school" size="xs" color="blue" /> CW filled
            </div>
            <div v-if="plan.hw" class="preview-item">
              <q-icon name="home_work" size="xs" color="orange" /> HW filled
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- By Classroom View -->
    <div v-show="viewTab === 'by-classroom'" class="classrooms-grid">
      <div 
        v-for="classroom in classroomPlans" 
        :key="classroom.name"
        class="classroom-card q-mb-lg"
      >
        <q-card flat bordered>
          <!-- Classroom Header -->
          <div class="classroom-header bg-primary text-white q-pa-md">
            <h5 class="q-ma-none flex items-center q-gutter-sm">
              <q-icon name="meeting_room" />
              {{ classroom.name }}
              <q-chip 
                dense 
                :label="`${classroom.plans.length} classes`"
                text-color="white"
              />
            </h5>
          </div>

          <!-- Plans Table -->
          <q-table
            flat
            bordered
            :rows="classroom.plans"
            :columns="classroomTableColumns"
            row-key="id"
            dense
            class="classroom-table"
            @row-click="(evt, row) => editPlan(row.data)"
          >
            <!-- Day Column -->
            <template #body-cell-day="props">
              <q-td :props="props">
                <strong>{{ days[props.row.data.schedule?.day] || 'N/A' }}</strong>
              </q-td>
            </template>

            <!-- Period Column -->
            <template #body-cell-period="props">
              <q-td :props="props" class="text-center">
                <q-badge :label="`P${props.row.data.schedule?.period_number}`" />
              </q-td>
            </template>

            <!-- Subject Column -->
            <template #body-cell-subject="props">
              <q-td :props="props">
                <span 
                  class="subject-badge"
                  :style="{ 
                    backgroundColor: props.row.data.schedule?.cst?.c_bg,
                    color: props.row.data.schedule?.cst?.c_text
                  }"
                >
                  {{ props.row.data.schedule?.cst?.subject_name }}
                </span>
              </q-td>
            </template>

            <!-- Status Column -->
            <template #body-cell-status="props">
              <q-td :props="props">
                <StatusBadge :status="props.row.data.status" />
              </q-td>
            </template>

            <!-- Classwork Column -->
            <template #body-cell-cw="props">
              <q-td :props="props" class="content-preview">
                <div v-if="props.row.data.cw" class="text-info">
                  <q-icon name="school" size="xs" /> 
                  <span class="q-ml-xs">{{ truncateText(props.row.data.cw, 30) }}</span>
                </div>
                <span v-else class="text-grey-5">-</span>
              </q-td>
            </template>

            <!-- Homework Column -->
            <template #body-cell-hw="props">
              <q-td :props="props" class="content-preview">
                <div v-if="props.row.data.hw" class="text-warning">
                  <q-icon name="home_work" size="xs" /> 
                  <span class="q-ml-xs">{{ truncateText(props.row.data.hw, 30) }}</span>
                </div>
                <span v-else class="text-grey-5">-</span>
              </q-td>
            </template>

            <!-- Notes Column -->
            <template #body-cell-notes="props">
              <q-td :props="props" class="content-preview">
                <span v-if="props.row.data.notes" class="text-info">
                  {{ truncateText(props.row.data.notes, 20) }}
                </span>
                <span v-else class="text-grey-5">-</span>
              </q-td>
            </template>
          </q-table>
        </q-card>
      </div>

      <!-- No selected classrooms -->
      <div v-if="!selectedClassrooms || selectedClassrooms.length === 0" class="text-center q-pa-xl">
        <q-icon name="meeting_room" size="64px" color="grey-5" />
        <p class="text-h6 text-grey-7 q-mt-md">No classrooms selected</p>
        <p class="text-grey-6">Select classrooms from the filter above to view by classroom</p>
      </div>
    </div>

    <!-- Edit Dialog -->
    <WeeklyPlanEditor
      v-model="showEditor"
      :plan="selectedPlan"
      :saving="saving"
      @submit="handleSave"
    />

    <!-- Print Preview Dialog -->
    <q-dialog v-model="showPrintPreview" maximized>
      <q-card class="full-height print-preview-card">
        <!-- Toolbar -->
        <q-toolbar class="bg-primary text-white">
          <q-toolbar-title>Print Preview - A4 Format</q-toolbar-title>
          <q-space />
          <q-btn
            icon="print"
            label="Print"
            color="white"
            flat
            @click="printPreview"
          />
          <q-btn icon="close" flat round dense @click="showPrintPreview = false" />
        </q-toolbar>

        <!-- Preview Container -->
        <div class="preview-container q-pa-md">
          <div id="print-area" class="a4-page">
            <!-- Header -->
            <div class="print-header q-mb-lg">
              <h2 class="q-ma-none">Weekly Plans</h2>
              <p class="q-ma-xs text-grey-7">
                Week {{ weekNumber }} - Semester {{ semesterNumber }}
              </p>
              <p class="q-ma-xs text-grey-7">
                Classroom: {{ selectedClassrooms.join(', ') }}
              </p>
              <p class="q-ma-xs text-grey-7">
                {{ new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) }}
              </p>
            </div>

            <!-- Plans Table -->
            <table class="print-table">
              <thead>
                <tr>
                  <th>Day</th>
                  <th>Period</th>
                  <th>Subject</th>
                  <th>Classroom</th>
                  <th>Classwork (CW)</th>
                  <th>Homework (HW)</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="plan in filteredPlans" :key="plan.id">
                  <td>{{ days[plan.schedule?.day] || 'N/A' }}</td>
                  <td class="text-center">P{{ plan.schedule?.period_number }}</td>
                  <td>{{ plan.schedule?.cst?.subject_name }}</td>
                  <td>{{ plan.schedule?.cst?.classroom_name }}</td>
                  <td class="content-cell">{{ plan.cw || '-' }}</td>
                  <td class="content-cell">{{ plan.hw || '-' }}</td>
                  <td class="content-cell">{{ plan.notes || '-' }}</td>
                </tr>
              </tbody>
            </table>

            <!-- Footer -->
            <div class="print-footer q-mt-lg">
              <p class="text-caption text-grey-6">
                Generated: {{ new Date().toLocaleString() }}
              </p>
            </div>
          </div>
        </div>
      </q-card>
    </q-dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useQuasar } from 'quasar'
import axios from 'axios'
import WeekSelector from '../components/weekly-plans/WeekSelector.vue'
import WeeklyPlanEditor from '../components/weekly-plans/WeeklyPlanEditor.vue'
import StatusBadge from '../components/shared/StatusBadge.vue'
import WeeklyPlanMenu from '../WeeklyPlanMenu.vue'

const $q = useQuasar()

// Data
const weeklyPlans = ref([])
const weekNumber = ref(1)
const semesterNumber = ref(1)
const maxWeeks = ref(18)
const currentWeek = ref(1)

// Filters
const selectedClassrooms = ref([])
const selectedDays = ref([])

// Copy/Paste state
const copiedData = ref(null)
const copyingPlanId = ref(null)

// Dialog state
const showEditor = ref(false)
const selectedPlan = ref(null)
const saving = ref(false)
const showPrintPreview = ref(false)
const viewTab = ref('by-day')

// Loading
const loading = ref(false)

const days = {
  1: 'Sunday',
  2: 'Monday',
  3: 'Tuesday',
  4: 'Wednesday',
  5: 'Thursday'
}

// Computed
const classroomOptions = computed(() => {
  const classrooms = new Set()
  weeklyPlans.value.forEach(p => {
    if (p.schedule?.cst?.classroom_name) {
      classrooms.add(p.schedule.cst.classroom_name)
    }
  })
  return Array.from(classrooms).sort()
})

const dayOptions = Object.entries(days).map(([value, label]) => ({
  label,
  value: parseInt(value)
}))

const filteredPlans = computed(() => {
  let plans = weeklyPlans.value

  if (selectedClassrooms.value?.length) {
    plans = plans.filter(p => selectedClassrooms.value.includes(p.schedule?.cst?.classroom_name))
  }

  if (selectedDays.value?.length) {
    plans = plans.filter(p => selectedDays.value.includes(p.schedule?.day))
  }

  return plans
})

const sortedPlansByDay = computed(() => {
  const byDay = {}
  
  filteredPlans.value.forEach(plan => {
    const dayNum = plan.schedule?.day
    if (!byDay[dayNum]) {
      byDay[dayNum] = {
        dayNumber: dayNum,
        dayName: days[dayNum] || `Day ${dayNum}`,
        plans: []
      }
    }
    byDay[dayNum].plans.push(plan)
  })

  // Sort plans within each day by period
  Object.values(byDay).forEach(day => {
    day.plans.sort((a, b) => a.schedule?.period_number - b.schedule?.period_number)
  })

  return Object.values(byDay).sort((a, b) => a.dayNumber - b.dayNumber)
})

const completionPercentage = computed(() => {
  const total = weeklyPlans.value.length
  if (!total) return 0
  const completed = weeklyPlans.value.filter(p => p.status === 'completed').length
  return Math.round((completed / total) * 100)
})

const progressColor = computed(() => {
  const p = completionPercentage.value
  if (p >= 80) return 'green'
  if (p >= 50) return 'amber'
  return 'red'
})

const classroomPlans = computed(() => {
  const byClassroom = {}
  
  filteredPlans.value.forEach(plan => {
    const classroomName = plan.schedule?.cst?.classroom_name
    if (!byClassroom[classroomName]) {
      byClassroom[classroomName] = {
        name: classroomName,
        plans: []
      }
    }
    byClassroom[classroomName].plans.push({
      id: plan.id,
      data: plan
    })
  })

  // Sort plans within each classroom by day and period
  Object.values(byClassroom).forEach(classroom => {
    classroom.plans.sort((a, b) => {
      const dayDiff = (a.data.schedule?.day || 0) - (b.data.schedule?.day || 0)
      if (dayDiff !== 0) return dayDiff
      return (a.data.schedule?.period_number || 0) - (b.data.schedule?.period_number || 0)
    })
  })

  return Object.values(byClassroom).sort((a, b) => a.name.localeCompare(b.name))
})

const classroomTableColumns = [
  { name: 'day', label: 'Day', field: row => days[row.data.schedule?.day] || 'N/A', align: 'left' },
  { name: 'period', label: 'Period', field: row => row.data.schedule?.period_number, align: 'center' },
  { name: 'subject', label: 'Subject', field: row => row.data.schedule?.cst?.subject_name, align: 'left' },
  { name: 'status', label: 'Status', field: row => row.data.status, align: 'left' },
  { name: 'cw', label: 'Classwork (CW)', field: row => row.data.cw, align: 'left' },
  { name: 'hw', label: 'Homework (HW)', field: row => row.data.hw, align: 'left' },
  { name: 'notes', label: 'Notes', field: row => row.data.notes, align: 'left' }
]

// Methods
const getStatus = (plan) => {
  const hasCw = !!plan.cw?.trim()
  const hasHw = !!plan.hw?.trim()
  if (!hasCw && !hasHw) return 'empty'
  if (hasCw && hasHw) return 'completed'
  return 'partial'
}

const truncateText = (text, length) => {
  if (!text) return ''
  return text.length > length ? text.substring(0, length) + '...' : text
}

const getPlanStyle = (plan) => {
  return {
    backgroundColor: plan.schedule?.cst?.c_bg || '#e0e0e0',
    color: plan.schedule?.cst?.c_text || '#333'
  }
}

const fetchPlans = async () => {
  loading.value = true
  try {
    const response = await axios.get('/weekly-system/api/teacher/my-weekly-plans', {
      params: {
        week_number: weekNumber.value,
        semester_number: semesterNumber.value
      }
    })
    weeklyPlans.value = (response.data.data || response.data || []).map(plan => ({
      ...plan,
      status: getStatus(plan)
    }))
  } catch (error) {
    console.error('Error fetching plans:', error)
    $q.notify({ type: 'negative', message: 'Failed to load weekly plans' })
  } finally {
    loading.value = false
  }
}

const editPlan = (plan) => {
  if (copiedData.value) return // Prevent edit mode when in paste mode if needed, or just let them both work
  selectedPlan.value = plan
  showEditor.value = true
}

const copyPlan = (plan, event) => {
  event.stopPropagation()
  copiedData.value = {
    cw: plan.cw,
    hw: plan.hw,
    notes: plan.notes
  }
  copyingPlanId.value = plan.id
  $q.notify({
    message: 'Data copied. Click "Paste" on other cards to apply.',
    color: 'info',
    icon: 'content_copy',
    timeout: 2000
  })
}

const cancelSelection = (event) => {
  event.stopPropagation()
  copiedData.value = null
  copyingPlanId.value = null
}

const pastePlan = async (plan, event) => {
  event.stopPropagation()
  if (!copiedData.value) return

  try {
    await axios.put(`/weekly-system/api/weekly-plans/${plan.id}`, {
      ...copiedData.value
    })
    
    // Update local state to avoid full re-fetch
    plan.cw = copiedData.value.cw
    plan.hw = copiedData.value.hw
    plan.notes = copiedData.value.notes
    plan.status = getStatus(plan)
    
    $q.notify({ type: 'positive', message: 'Data pasted successfully!' })
  } catch (error) {
    console.error('Error pasting plan:', error)
    $q.notify({ type: 'negative', message: 'Failed to paste data' })
  }
}

const handleSave = async (formData) => {
  saving.value = true
  try {
    await axios.put(`/weekly-system/api/weekly-plans/${formData.id}`, {
      cw: formData.cw,
      hw: formData.hw,
      notes: formData.notes
    })
    
    $q.notify({ type: 'positive', message: 'Weekly plan saved!' })
    showEditor.value = false
    await fetchPlans()
  } catch (error) {
    console.error('Error saving plan:', error)
    $q.notify({ type: 'negative', message: 'Failed to save plan' })
  } finally {
    saving.value = false
  }
}

const printPreview = () => {
  const printArea = document.getElementById('print-area')
  if (!printArea) {
    $q.notify({ type: 'negative', message: 'Print area not found' })
    return
  }

  // Create a new window for printing
  const printWindow = window.open('', '_blank')
  printWindow.document.write(`
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Weekly Plans - Print</title>
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        @page {
          size: A4;
          margin: 10mm;
        }
        
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          background-color: white;
          color: #333;
          line-height: 1.4;
        }
        
        .print-header {
          margin-bottom: 24px;
          border-bottom: 2px solid #1976d2;
          padding-bottom: 12px;
        }
        
        .print-header h2 {
          font-size: 24px;
          color: #1976d2;
          margin-bottom: 8px;
        }
        
        .print-header p {
          font-size: 12px;
          color: #666;
          margin: 4px 0;
        }
        
        .print-table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
          font-size: 11px;
        }
        
        .print-table thead {
          background-color: #f5f5f5;
          border-bottom: 2px solid #1976d2;
        }
        
        .print-table th {
          padding: 10px;
          text-align: left;
          font-weight: 600;
          color: #1976d2;
          border: 1px solid #ddd;
        }
        
        .print-table td {
          padding: 10px;
          border: 1px solid #ddd;
          word-wrap: break-word;
          overflow-wrap: break-word;
        }
        
        .print-table tbody tr:nth-child(even) {
          background-color: #f9f9f9;
        }
        
        .print-table tbody tr:hover {
          background-color: #f0f0f0;
        }
        
        .text-center {
          text-align: center;
        }
        
        .content-cell {
          max-width: 120px;
          white-space: pre-wrap;
        }
        
        .print-footer {
          margin-top: 20px;
          border-top: 1px solid #ddd;
          padding-top: 10px;
          text-align: right;
          font-size: 10px;
          color: #999;
        }
        
        @media print {
          body {
            background-color: white;
          }
          
          .print-table {
            page-break-inside: avoid;
          }
          
          .print-table tbody tr {
            page-break-inside: avoid;
          }
        }
      </style>
    </head>
    <body>
      ${printArea.innerHTML}
    </body>
    </html>
  `)
  
  printWindow.document.close()
  
  // Wait for content to load before printing
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print()
      printWindow.close()
    }, 250)
  }
}

// Watchers
watch([weekNumber, semesterNumber], () => {
  fetchPlans()
})

// Lifecycle
onMounted(() => {
  // Calculate current week
  const now = new Date()
  const startOfYear = new Date(now.getFullYear(), 0, 1)
  currentWeek.value = Math.ceil(((now - startOfYear) / 86400000 + startOfYear.getDay() + 1) / 7)
  weekNumber.value = currentWeek.value > maxWeeks.value ? 1 : currentWeek.value

  fetchPlans()
})
</script>

<style scoped>
h4 {
  font-size: 1.5rem;
}

.plans-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 16px;
}

.day-column {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.day-header {
  background: var(--q-primary);
  color: white;
  padding: 12px;
  border-radius: 8px;
  text-align: center;
  font-weight: 600;
}

.plan-card {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.plan-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.plan-card.is-completed {
  border-left: 4px solid var(--q-positive);
}

.plan-card.is-partial {
  border-left: 4px solid var(--q-warning);
}

.plan-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border-radius: 6px;
  margin-bottom: 8px;
}

.period-badge {
  font-weight: bold;
  font-size: 0.75rem;
}

.subject-name {
  font-weight: 600;
  font-size: 0.85rem;
}

.classroom {
  margin-bottom: 8px;
}

.plan-status {
  margin-bottom: 8px;
}

.plan-preview {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.preview-item {
  display: flex;
  align-items: center;
  gap: 4px;
}

@media (max-width: 1024px) {
  .plans-grid {
    grid-template-columns: repeat(3, 1fr);
  }
}

@media (max-width: 768px) {
  .plans-grid {
    grid-template-columns: 1fr;
  }
}

/* Print Preview Styles */
.print-preview-card {
  background-color: #f5f5f5;
}

.preview-container {
  height: calc(100vh - 64px);
  overflow-y: auto;
  display: flex;
  justify-content: center;
  padding: 24px;
}

.a4-page {
  width: 210mm;
  height: 297mm;
  background-color: white;
  padding: 20mm;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
  margin: auto;
}

.print-header {
  margin-bottom: 24px;
  border-bottom: 2px solid var(--q-primary);
  padding-bottom: 12px;
}

.print-header h2 {
  font-size: 24px;
  color: var(--q-primary);
  margin-bottom: 8px;
}

.print-header p {
  font-size: 12px;
  color: #666;
  margin: 4px 0;
}

.print-table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 20px;
  font-size: 11px;
}

.print-table thead {
  background-color: #f5f5f5;
  border-bottom: 2px solid var(--q-primary);
}

.print-table th {
  padding: 10px;
  text-align: left;
  font-weight: 600;
  color: var(--q-primary);
  border: 1px solid #ddd;
}

.print-table td {
  padding: 10px;
  border: 1px solid #ddd;
  word-wrap: break-word;
  overflow-wrap: break-word;
}

.print-table tbody tr:nth-child(even) {
  background-color: #f9f9f9;
}

.print-table tbody tr:hover {
  background-color: #f0f0f0;
}

.content-cell {
  max-width: 120px;
  white-space: pre-wrap;
  word-break: break-word;
}

.print-footer {
  margin-top: 20px;
  border-top: 1px solid #ddd;
  padding-top: 10px;
  text-align: right;
  font-size: 10px;
  color: #999;
}

@media print {
  body {
    background-color: white;
    margin: 0;
    padding: 0;
  }
  
  .preview-container {
    background-color: white;
    padding: 0;
    height: auto;
  }
  
  .a4-page {
    width: 100%;
    height: auto;
    box-shadow: none;
    margin: 0;
    padding: 10mm;
    page-break-after: always;
  }
  
  .print-table {
    page-break-inside: avoid;
  }
  
  .print-table tbody tr {
    page-break-inside: avoid;
  }
}

/* Classroom View Styles */
.classrooms-grid {
  display: grid;
  gap: 16px;
}

.classroom-card {
  cursor: default;
}

.classroom-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.classroom-header h5 {
  margin: 0;
  font-size: 1rem;
}

.classroom-table {
  font-size: 0.9rem;
}

.classroom-table :deep(.q-table__card) {
  box-shadow: none;
}

.classroom-table :deep(tbody tr) {
  cursor: pointer;
  transition: background-color 0.2s ease;
}

.classroom-table :deep(tbody tr:hover) {
  background-color: rgba(25, 118, 210, 0.05);
}

.subject-badge {
  display: inline-block;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: 600;
  font-size: 0.85rem;
}

.content-preview {
  font-size: 0.85rem;
  max-width: 150px;
  word-wrap: break-word;
  overflow-wrap: break-word;
}

.content-preview .text-info {
  color: #0288d1;
}

.content-preview .text-warning {
  color: #ffa726;
}

.content-preview .text-grey-5 {
  color: #bdbdbd;
}

@media (max-width: 768px) {
  .classroom-table {
    font-size: 0.8rem;
  }
  
  .classroom-header h5 {
    font-size: 0.9rem;
  }
  
  .content-preview {
    max-width: 100px;
  }
}
</style>
