<template>
  <div class="q-pa-md">
    <!-- Page Header -->
    <div class="row items-center q-mb-lg">
      <div class="col">
        <h4 class="q-ma-none text-weight-bold">
          <q-icon name="edit_note" class="q-mr-sm" color="primary" />
          My Weekly Plans
        </h4>
        <p class="text-grey-7 q-mb-none">
          Fill in your classwork and homework for each class
        </p>
      </div>
    </div>

    <!-- Controls -->
    <q-card flat bordered class="q-pa-md q-mb-lg">
      <div class="row q-gutter-md items-center">
        <!-- Week Selector -->
        <div class="col-12 col-sm-6 col-md-4">
          <WeekSelector
            v-model="weekNumber"
            :max-weeks="maxWeeks"
            :current-week="currentWeek"
          />
        </div>

        <!-- Semester -->
        <div class="col-12 col-sm-3 col-md-2">
          <q-select
            v-model="semesterNumber"
            :options="[{ label: 'Semester 1', value: 1 }, { label: 'Semester 2', value: 2 }]"
            label="Semester"
            outlined
            dense
            emit-value
            map-options
          />
        </div>

        <!-- Progress Summary -->
        <div class="col-auto q-ml-auto">
          <q-linear-progress
            :value="completionPercentage / 100"
            size="25px"
            :color="progressColor"
            track-color="grey-3"
            rounded
            style="width: 150px"
          >
            <div class="absolute-full flex flex-center">
              <span class="text-caption text-weight-bold">{{ completionPercentage }}%</span>
            </div>
          </q-linear-progress>
        </div>
      </div>
    </q-card>

    <!-- Loading State -->
    <div v-if="loading" class="row justify-center q-pa-xl">
      <q-spinner-dots size="50px" color="primary" />
    </div>

    <!-- Empty State -->
    <q-card v-else-if="!weeklyPlans.length" flat bordered class="text-center q-pa-xl">
      <q-icon name="event_note" size="64px" color="grey-5" />
      <p class="text-h6 text-grey-7 q-mt-md">No plans for this week</p>
      <p class="text-grey-6">Plans will appear once generated by admin</p>
    </q-card>

    <!-- Weekly Plans Grid -->
    <div v-else class="plans-grid">
      <div v-for="day in sortedPlansByDay" :key="day.dayNumber" class="day-column">
        <div class="day-header">{{ day.dayName }}</div>
        
        <div
          v-for="plan in day.plans"
          :key="plan.id"
          class="plan-card"
          :class="{ 'is-completed': plan.status === 'completed', 'is-partial': plan.status === 'partial' }"
          @click="editPlan(plan)"
        >
          <!-- Subject & Period -->
          <div class="plan-header" :style="getPlanStyle(plan)">
            <span class="period-badge">P{{ plan.schedule?.period_number }}</span>
            <span class="subject-name">{{ plan.schedule?.cst?.subject_name }}</span>
          </div>

          <!-- Classroom -->
          <div class="classroom text-caption text-grey-7">
            <q-icon name="meeting_room" size="xs" />
            {{ plan.schedule?.cst?.classroom_name }}
          </div>

          <!-- Status -->
          <div class="plan-status">
            <StatusBadge :status="plan.status" />
          </div>

          <!-- Preview -->
          <div v-if="plan.cw || plan.hw" class="plan-preview text-caption">
            <div v-if="plan.cw" class="preview-item">
              <q-icon name="school" size="xs" color="blue" /> CW filled
            </div>
            <div v-if="plan.hw" class="preview-item">
              <q-icon name="home_work" size="xs" color="orange" /> HW filled
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Edit Dialog -->
    <WeeklyPlanEditor
      v-model="showEditor"
      :plan="selectedPlan"
      :saving="saving"
      @submit="handleSave"
    />
  </div>
</template>

<script setup>
import { ref, computed, onMounted, watch } from 'vue'
import { useQuasar } from 'quasar'
import axios from 'axios'
import WeekSelector from '../components/weekly-plans/WeekSelector.vue'
import WeeklyPlanEditor from '../components/weekly-plans/WeeklyPlanEditor.vue'
import StatusBadge from '../components/shared/StatusBadge.vue'

const $q = useQuasar()

// Data
const weeklyPlans = ref([])
const weekNumber = ref(1)
const semesterNumber = ref(1)
const maxWeeks = ref(18)
const currentWeek = ref(1)

// Dialog state
const showEditor = ref(false)
const selectedPlan = ref(null)
const saving = ref(false)

// Loading
const loading = ref(false)

const days = {
  1: 'Sunday',
  2: 'Monday',
  3: 'Tuesday',
  4: 'Wednesday',
  5: 'Thursday'
}

// Computed
const sortedPlansByDay = computed(() => {
  const byDay = {}
  
  weeklyPlans.value.forEach(plan => {
    const dayNum = plan.schedule?.day_number
    if (!byDay[dayNum]) {
      byDay[dayNum] = {
        dayNumber: dayNum,
        dayName: days[dayNum] || `Day ${dayNum}`,
        plans: []
      }
    }
    byDay[dayNum].plans.push(plan)
  })

  // Sort plans within each day by period
  Object.values(byDay).forEach(day => {
    day.plans.sort((a, b) => a.schedule?.period_number - b.schedule?.period_number)
  })

  return Object.values(byDay).sort((a, b) => a.dayNumber - b.dayNumber)
})

const completionPercentage = computed(() => {
  const total = weeklyPlans.value.length
  if (!total) return 0
  const completed = weeklyPlans.value.filter(p => p.status === 'completed').length
  return Math.round((completed / total) * 100)
})

const progressColor = computed(() => {
  const p = completionPercentage.value
  if (p >= 80) return 'green'
  if (p >= 50) return 'amber'
  return 'red'
})

// Methods
const getStatus = (plan) => {
  const hasCw = !!plan.cw?.trim()
  const hasHw = !!plan.hw?.trim()
  if (!hasCw && !hasHw) return 'empty'
  if (hasCw && hasHw) return 'completed'
  return 'partial'
}

const getPlanStyle = (plan) => {
  return {
    backgroundColor: plan.schedule?.cst?.c_bg || '#e0e0e0',
    color: plan.schedule?.cst?.c_text || '#333'
  }
}

const fetchPlans = async () => {
  loading.value = true
  try {
    const response = await axios.get('/api/teacher/my-weekly-plans', {
      params: {
        week_number: weekNumber.value,
        semester_number: semesterNumber.value
      }
    })
    weeklyPlans.value = (response.data.data || response.data || []).map(plan => ({
      ...plan,
      status: getStatus(plan)
    }))
  } catch (error) {
    console.error('Error fetching plans:', error)
    $q.notify({ type: 'negative', message: 'Failed to load weekly plans' })
  } finally {
    loading.value = false
  }
}

const editPlan = (plan) => {
  selectedPlan.value = plan
  showEditor.value = true
}

const handleSave = async (formData) => {
  saving.value = true
  try {
    await axios.put(`/api/weekly-plans/${formData.id}`, {
      cw: formData.cw,
      hw: formData.hw,
      notes: formData.notes
    })
    
    $q.notify({ type: 'positive', message: 'Weekly plan saved!' })
    showEditor.value = false
    await fetchPlans()
  } catch (error) {
    console.error('Error saving plan:', error)
    $q.notify({ type: 'negative', message: 'Failed to save plan' })
  } finally {
    saving.value = false
  }
}

// Watchers
watch([weekNumber, semesterNumber], () => {
  fetchPlans()
})

// Lifecycle
onMounted(() => {
  // Calculate current week
  const now = new Date()
  const startOfYear = new Date(now.getFullYear(), 0, 1)
  currentWeek.value = Math.ceil(((now - startOfYear) / 86400000 + startOfYear.getDay() + 1) / 7)
  weekNumber.value = currentWeek.value > maxWeeks.value ? 1 : currentWeek.value

  fetchPlans()
})
</script>

<style scoped>
h4 {
  font-size: 1.5rem;
}

.plans-grid {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 16px;
}

.day-column {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.day-header {
  background: var(--q-primary);
  color: white;
  padding: 12px;
  border-radius: 8px;
  text-align: center;
  font-weight: 600;
}

.plan-card {
  background: white;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  padding: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
}

.plan-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateY(-2px);
}

.plan-card.is-completed {
  border-left: 4px solid var(--q-positive);
}

.plan-card.is-partial {
  border-left: 4px solid var(--q-warning);
}

.plan-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border-radius: 6px;
  margin-bottom: 8px;
}

.period-badge {
  font-weight: bold;
  font-size: 0.75rem;
}

.subject-name {
  font-weight: 600;
  font-size: 0.85rem;
}

.classroom {
  margin-bottom: 8px;
}

.plan-status {
  margin-bottom: 8px;
}

.plan-preview {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.preview-item {
  display: flex;
  align-items: center;
  gap: 4px;
}

@media (max-width: 1024px) {
  .plans-grid {
    grid-template-columns: repeat(3, 1fr);
  }
}

@media (max-width: 768px) {
  .plans-grid {
    grid-template-columns: 1fr;
  }
}
</style>
