<?php

namespace App\Http\Controllers\MyClass2026\Cr;

use App\Http\Controllers\Controller;
use App\Models\Classroom;
use App\Models\Subject;
use App\Models\Teacher;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Inertia\Inertia;

class ClassroomRecordsPageController extends Controller
{
    /**
     * Display the Classroom Records page
     * 
     * This serves the main Vue component for tracking student classroom records.
     * Supports two modes:
     * - Standalone: Teacher selects classroom/subject/date from dropdowns
     * - Deep Link: Opened from teacher schedule with pre-filled context
     */
    public function __invoke(Request $request)
    {
        $user = Auth::user();
        
        // Get school and year context
        $schoolId = $user->currentSchoolId();
        $yearId = $user->currentAcademicYearId();
        
        // Check if user is admin (read-only mode)
        $isAdmin = $user->hasAnyRole(['admin', 'school_admin', 'super_admin']);
        
        // Get initial context from query params (for deep linking from schedule)
        $initialContext = null;
        $teacherId = null;
        
        // Get teacher record — look up by user_id only first (avoids school_id circular dependency)
        // Then confirm it belongs to the resolved school
        $teacherRecord = Teacher::where('user_id', $user->id)
            ->when($schoolId, fn ($q) => $q->where('school_id', $schoolId))
            ->first();
        
        if ($teacherRecord) {
            $teacherId = $teacherRecord->id;
            // Override school_id with teacher's school_id if user doesn't have one
            if (!$schoolId && $teacherRecord->school_id) {
                $schoolId = $teacherRecord->school_id;
            }
        }
        
        if ($request->has('classroom_id') && $request->has('subject_id')) {
            // Deep link from teacher schedule
            $classroomId = $request->query('classroom_id');
            $subjectId = $request->query('subject_id');
            $date = $request->query('date', now()->toDateString());
            
            // Verify teacher is assigned to this classroom+subject (unless admin)
            if (!$isAdmin) {
                // Check in classroom_subject_teachers table
                $assignment = DB::table('classroom_subject_teachers')
                    ->where('classroom_id', $classroomId)
                    ->where('subject_id', $subjectId)
                    ->where('school_id', $schoolId)
                    ->first();
                
                // If no teacher record exists yet, create one from the assignment
                if (!$teacherRecord && $assignment) {
                    $teacherRecord = Teacher::firstOrCreate(
                        ['user_id' => $user->id, 'school_id' => $schoolId],
                        ['name' => $user->name, 'email' => $user->email]
                    );
                    $teacherId = $teacherRecord->id;
                    
                    // Update the assignment with the new teacher_id
                    DB::table('classroom_subject_teachers')
                        ->where('id', $assignment->id)
                        ->update(['teacher_id' => $teacherId]);
                }
                
                if (!$assignment && !$teacherRecord) {
                    abort(403, 'You are not assigned to teach this classroom-subject combination');
                }
            }
            
            // Get day_number and period_number from schedule if available
            $dayNumber = $request->query('day_number', 1);
            $periodNumber = $request->query('period_number', 1);
            
             $initialContext = [
                'classroom_id' => $classroomId,
                'subject_id' => $subjectId,
                'teacher_id' => $teacherId, // Use resolved teacher_id
                'date' => $date,
                'day_number' => (int) $dayNumber,
                'period_number' => (int) $periodNumber,
                'period_code' => '', // Will be generated by frontend
                'classroom_name' => $request->query('classroom_name'),
                'subject_name' => $request->query('subject_name'),
            ];
        }
        
        // Get available classrooms and subjects for standalone mode
        $classrooms = [];
        $subjects = [];
        
        Log::info('CR Page: isAdmin=' . ($isAdmin ? 'true' : 'false') . ', initialContext=' . ($initialContext ? 'true' : 'false') . ', teacherId=' . ($teacherId ?? 'NULL') . ', classrooms count=' . count($classrooms) . ', subjects count=' . count($subjects));
        
        if (!$initialContext) {
            // Get teacher's assigned classrooms and subjects from classroom_subject_teachers
            // ALWAYS filter by teacher_id if teacher record exists (even for admins)
            $query = DB::table('classroom_subject_teachers')
                ->whereNull('classroom_subject_teachers.deleted_at')
                ->join('classrooms', 'classroom_subject_teachers.classroom_id', '=', 'classrooms.id')
                ->join('subjects', 'classroom_subject_teachers.subject_id', '=', 'subjects.id')
                ->select('classrooms.id as classroom_id', 'classrooms.name as classroom_name',
                         'subjects.id as subject_id', 'subjects.name as subject_name');

            if ($teacherId) {
                // Teacher is registered — filter by their assignments ONLY
                $query->where('classroom_subject_teachers.teacher_id', $teacherId);
                Log::info('CR Page: Loading assignments for teacher_id=' . $teacherId);
            } elseif ($isAdmin) {
                // Admin without teacher record — show all classrooms/subjects
                Log::info('CR Page: Admin without teacher record, showing all');
            } else {
                // No teacher record and not admin — filter by school/year (shouldn't happen)
                Log::warning('CR Page: No teacher record found for user ' . $user->id . ' in school ' . $schoolId);
                $query->where('classroom_subject_teachers.school_id', $schoolId);
                if ($yearId) {
                    $query->where('classroom_subject_teachers.academic_year_id', $yearId);
                }
            }

            $assignments = $query->get();
            
            Log::info('CR Page: Found ' . $assignments->count() . ' assignments for teacher_id=' . $teacherId . ' school=' . $schoolId . ' year=' . $yearId);
            
            $classrooms = $assignments->unique('classroom_id')->map(function($item) {
                return ['id' => $item->classroom_id, 'name' => $item->classroom_name];
            })->values()->toArray();
            
            $subjects = $assignments->unique('subject_id')->map(function($item) {
                return ['id' => $item->subject_id, 'name' => $item->subject_name];
            })->values()->toArray();
            
            Log::info('CR Page: FINAL - classrooms=' . count($classrooms) . ', subjects=' . count($subjects));
            
            // If admin has teacher record, they should see teacher-specific data (not all)
            if ($isAdmin && $teacherId) {
                Log::info('CR Page: Admin user with teacher record - showing teacher-specific assignments');
            }
        } elseif ($isAdmin && !$teacherId) {
            // Admin sees all classrooms and subjects
            $classrooms = Classroom::where('school_id', $schoolId)
                ->orderBy('name')
                ->get(['id', 'name'])
                ->toArray();
            
            $subjects = Subject::where('school_id', $schoolId)
                ->orderBy('name')
                ->get(['id', 'name'])
                ->toArray();
        }
        // Get available grades for category scoping
        $grades = \App\Models\Grade::where('school_id', $schoolId)
            ->orderBy('name')
            ->get(['id', 'name'])
            ->toArray();

        // return $classrooms;
        return Inertia::render('myclass2026/features/cr/classroom_records_v1/ClassroomRecordsPage', [
            'initialContext' => $initialContext,
            'isAdmin' => $isAdmin,
            'classrooms' => $classrooms,
            'subjects' => $subjects,
            'grades' => $grades,
            'teacherId' => $teacherId, // Pass resolved teacher_id
            'academicContext' => [
                'year_id' => $yearId,
                'semester' => 1, // TODO: Get current semester
            ],
        ]);
    }
}
