<template>
  <q-dialog :model-value="modelValue" @update:model-value="$emit('update:modelValue', $event)" persistent>
    <q-card style="min-width: 700px; max-width: 900px">
      <q-card-section class="row items-center q-pb-none">
        <q-icon name="upload_file" color="secondary" size="md" class="q-mr-sm" />
        <div class="text-h6">Bulk Import Menus</div>
        <q-space />
        <q-btn icon="close" flat round dense @click="handleClose" />
      </q-card-section>

      <q-card-section>
        <q-stepper
          v-model="step"
          vertical
          color="primary"
          animated
        >
          <!-- Step 1: Generate AI Prompt -->
          <q-step
            :name="1"
            title="Generate AI Prompt"
            icon="smart_toy"
            :done="step > 1"
          >
            <div class="text-body2 q-mb-md">
              Click the button below to generate a prompt that you can copy and paste to an AI assistant (ChatGPT, Claude, etc.) to generate menu JSON.
            </div>

            <q-btn
              color="purple"
              icon="content_copy"
              label="Generate & Copy AI Prompt"
              @click="generateAIPrompt"
              :loading="loadingPrompt"
            />

            <q-banner v-if="aiPrompt" class="bg-grey-2 q-mt-md" rounded>
              <template v-slot:avatar>
                <q-icon name="info" color="primary" />
              </template>
              <div class="text-subtitle2 q-mb-sm">AI Prompt (Copied to Clipboard)</div>
              <pre class="text-caption" style="white-space: pre-wrap; max-height: 200px; overflow-y: auto;">{{ aiPrompt }}</pre>
            </q-banner>

            <q-stepper-navigation>
              <q-btn color="primary" label="Next" @click="step = 2" />
            </q-stepper-navigation>
          </q-step>

          <!-- Step 2: Paste JSON -->
          <q-step
            :name="2"
            title="Paste JSON"
            icon="code"
            :done="step > 2"
          >
            <div class="text-body2 q-mb-md">
              Paste the JSON generated by the AI assistant below:
            </div>

            <q-input
              v-model="jsonInput"
              type="textarea"
              outlined
              rows="15"
              placeholder='[{"label": "Menu Label", "route": "route.name", ...}]'
              :error="!!jsonError"
              :error-message="jsonError"
            />

            <q-stepper-navigation>
              <q-btn flat color="grey-7" label="Back" @click="step = 1" class="q-mr-sm" />
              <q-btn color="primary" label="Validate" @click="validateJSON" :loading="validating" />
            </q-stepper-navigation>
          </q-step>

          <!-- Step 3: Preview & Import -->
          <q-step
            :name="3"
            title="Preview & Import"
            icon="preview"
          >
            <div class="text-body2 q-mb-md">
              Preview the menus that will be created:
            </div>

            <q-list bordered separator>
              <q-item v-for="(menu, index) in parsedMenus" :key="index">
                <q-item-section avatar>
                  <q-icon :name="menu.icon || 'folder'" />
                </q-item-section>
                <q-item-section>
                  <q-item-label>{{ menu.label }}</q-item-label>
                  <q-item-label caption>
                    Module: {{ menu.module }} | Route: {{ menu.route || 'None' }}
                  </q-item-label>
                  <q-item-label caption v-if="menu.children && menu.children.length > 0">
                    Children: {{ menu.children.length }}
                  </q-item-label>
                </q-item-section>
              </q-item>
            </q-list>

            <div class="q-mt-md">
              <q-checkbox v-model="dryRun" label="Dry run (preview only, don't save)" />
            </div>

            <q-stepper-navigation>
              <q-btn flat color="grey-7" label="Back" @click="step = 2" class="q-mr-sm" />
              <q-btn
                color="primary"
                :label="dryRun ? 'Run Dry Run' : 'Import Menus'"
                @click="importMenus"
                :loading="importing"
              />
            </q-stepper-navigation>
          </q-step>
        </q-stepper>

        <!-- Import Results -->
        <q-banner v-if="importResults" :class="importResults.error_count > 0 ? 'bg-warning' : 'bg-positive'" class="text-white q-mt-md" rounded>
          <template v-slot:avatar>
            <q-icon :name="importResults.error_count > 0 ? 'warning' : 'check_circle'" />
          </template>
          <div class="text-subtitle2">Import Results</div>
          <div class="text-body2">
            Success: {{ importResults.success_count }} | Errors: {{ importResults.error_count }}
          </div>
          
          <div v-if="importResults.results.errors.length > 0" class="q-mt-sm">
            <div class="text-subtitle2">Errors:</div>
            <ul class="q-mb-none">
              <li v-for="(error, index) in importResults.results.errors.slice(0, 5)" :key="index">
                {{ error.data?.label || `Item ${error.index}` }}: {{ Object.values(error.errors).flat().join(', ') }}
              </li>
            </ul>
            <div v-if="importResults.results.errors.length > 5" class="text-caption">
              ... and {{ importResults.results.errors.length - 5 }} more errors
            </div>
          </div>
        </q-banner>
      </q-card-section>

      <q-card-actions align="right">
        <q-btn flat label="Close" color="grey-7" @click="handleClose" />
      </q-card-actions>
    </q-card>
  </q-dialog>
</template>

<script setup>
import { ref } from 'vue';
import { useQuasar, copyToClipboard } from 'quasar';
import axios from 'axios';

defineProps({
  modelValue: Boolean,
});

const emit = defineEmits(['update:modelValue', 'imported']);

const $q = useQuasar();

// State
const step = ref(1);
const loadingPrompt = ref(false);
const validating = ref(false);
const importing = ref(false);
const aiPrompt = ref('');
const jsonInput = ref('');
const jsonError = ref('');
const parsedMenus = ref([]);
const dryRun = ref(true);
const importResults = ref(null);

// Methods
const generateAIPrompt = async () => {
  try {
    loadingPrompt.value = true;
    
    // Ensure CSRF cookie is set for Sanctum
    await axios.get('/sanctum/csrf-cookie');
    
    const response = await axios.get('/api/admin/menus/helpers/ai-prompt');
    aiPrompt.value = response.data.prompt;
    
    await copyToClipboard(aiPrompt.value);
    $q.notify({
      type: 'positive',
      message: 'AI prompt copied to clipboard!',
    });
  } catch (error) {
    console.error('Error generating AI prompt:', error);
    $q.notify({
      type: 'negative',
      message: error.response?.data?.message || 'Failed to generate AI prompt',
    });
  } finally {
    loadingPrompt.value = false;
  }
};

const validateJSON = () => {
  try {
    validating.value = true;
    jsonError.value = '';
    
    const parsed = JSON.parse(jsonInput.value);
    
    if (!Array.isArray(parsed)) {
      jsonError.value = 'JSON must be an array of menu objects';
      return;
    }
    
    parsedMenus.value = parsed;
    step.value = 3;
  } catch (error) {
    jsonError.value = `Invalid JSON: ${error.message}`;
  } finally {
    validating.value = false;
  }
};

const importMenus = async () => {
  try {
    importing.value = true;
    
    // Ensure CSRF cookie is set for Sanctum
    await axios.get('/sanctum/csrf-cookie');
    
    const response = await axios.post('/api/admin/menus/bulk-import', {
      menus: parsedMenus.value,
      dry_run: dryRun.value,
    });
    
    importResults.value = response.data;
    
    $q.notify({
      type: response.data.error_count > 0 ? 'warning' : 'positive',
      message: response.data.message,
    });
    
    if (!dryRun.value && response.data.error_count === 0) {
      emit('imported');
      setTimeout(() => handleClose(), 2000);
    }
  } catch (error) {
    console.error('Error importing menus:', error);
    $q.notify({
      type: 'negative',
      message: error.response?.data?.message || 'Failed to import menus',
    });
  } finally {
    importing.value = false;
  }
};

const handleClose = () => {
  step.value = 1;
  jsonInput.value = '';
  jsonError.value = '';
  parsedMenus.value = [];
  importResults.value = null;
  emit('update:modelValue', false);
};
</script>
